/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trx_jual;

import GUI.Dashboard2;
import static GUI.data_barang_1.jTable1;
import db.konekdb;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lutfi
 */
public class pilih_barang extends javax.swing.JInternalFrame {

    /**
     * Creates new form pilih_barang
     */
    public String id;

    public pilih_barang() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI gui = (BasicInternalFrameUI) this.getUI();
        gui.setNorthPane(null);
        Dimension desktopSize = Dashboard2.dpane.getSize();
        Dimension jInternalFrameSize = this.getSize();
        this.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
        loadtabel();
    }

    public void loadtabel() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Id barang");
        tbl.addColumn("Nama Barang");
        tbl.addColumn("Satuan");
        tbl.addColumn("Harga Jual");
        tbl.addColumn("Stok");
        jTable1.setModel(tbl);
        try {
            String sql = "SELECT tb_produk.id_produk, tb_produk.nama_produk, tb_produk.satuan, tb_produk.harga_jual, tb_stokbarang.stok_produk "
                    + "FROM tb_produk JOIN tb_stokbarang ON tb_produk.id_produk = tb_stokbarang.id_produk";
            java.sql.Connection conn = (Connection) konekdb.GetConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5)});
                jTable1.setModel(tbl);
            }
        } catch (Exception e) {
        }
    }

    public void search() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Id barang");
        tbl.addColumn("Nama Barang");
        tbl.addColumn("Satuan");
        tbl.addColumn("Harga Jual");
        tbl.addColumn("Stok");
        jTable1.setModel(tbl);
        String c = pencarian.getText();
        
        try {
        String sql = "SELECT tb_produk.id_produk, tb_produk.nama_produk, tb_produk.satuan, tb_produk.harga_jual, tb_stokbarang.stok_produk "
                    + "FROM tb_produk JOIN tb_stokbarang ON tb_produk.id_produk = tb_stokbarang.id_produk LIKE '%" + c + "%' OR nama_produk LIKE '%" + c + "%'";
            java.sql.Connection conn = (Connection) konekdb.GetConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet rs = stm.executeQuery(sql);
            while (rs.next()) {
                tbl.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5)});
                jTable1.setModel(tbl);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Join");
        }
        
        
//        try {
//            String sql1 = "SELECT * FROM tb_produk WHERE id_produk LIKE '%" + c + "%' OR nama_produk LIKE '%" + c + "%'";
//            java.sql.Connection con = (Connection) konekdb.GetConnection();
//            java.sql.Statement st = con.createStatement();
//            java.sql.ResultSet res = st.executeQuery(sql1);
//            while (res.next()) {
//                    tbl.addRow(new Object[]{
//                        res.getString(1),
//                        res.getString(2),
//                        res.getString(3),
//                        res.getString(4),
//                        res.getString(5)});
//                    jTable1.setModel(tbl);
//            }
//        } catch (Exception e) {
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pencarian = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_batal = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pencarian.setFont(new java.awt.Font("Quicksand", 0, 17)); // NOI18N
        pencarian.setBorder(null);
        pencarian.setOpaque(false);
        pencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pencarianKeyReleased(evt);
            }
        });
        getContentPane().add(pencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 290, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 630, 250));

        btn_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trx_jual/batal.png"))); // NOI18N
        btn_batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batalMouseClicked(evt);
            }
        });
        getContentPane().add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trx_jual/simpan.png"))); // NOI18N
        btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trx_jual/pilih barang.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            tambah_barang tb = new tambah_barang();
            tb.id_barang.setText(id);
            this.getDesktopPane().add(tb);
            tb.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_simpanMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            id = (String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0)));
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            getDesktopPane().add(new tambah_barang()).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_batalMouseClicked

    private void pencarianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pencarianKeyReleased
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_pencarianKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_batal;
    private javax.swing.JLabel btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pencarian;
    // End of variables declaration//GEN-END:variables
}
