/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trx_jual;

import GUI.Dashboard2;
import db.konekdb;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.text.NumberFormat;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Lutfi
 */
public class ubah_tjual extends javax.swing.JInternalFrame {

    /**
     * Creates new form ubah_tjual
     */
    public String idk;
    public int total, harga;

    public ubah_tjual(String id) {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI gui = (BasicInternalFrameUI) this.getUI();
        gui.setNorthPane(null);
        Dimension desktopSize = Dashboard2.dpane.getSize();
        Dimension jInternalFrameSize = this.getSize();
        this.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
        idk = id;
        try {
            String sql = "SELECT * FROM `temp_trx_jual` WHERE id_brg='" + id + "'";
            java.sql.Connection con = (java.sql.Connection) konekdb.GetConnection();
            java.sql.Statement pst = con.createStatement();
            java.sql.ResultSet rs = pst.executeQuery(sql);
            while (rs.next()) {
                nama_barang.setText(rs.getString("nama"));
                jumlah_barang.setText(rs.getString("jumlah"));
                try {
                    String sql1 = "SELECT * FROM `tb_barang` WHERE id_barang='" + rs.getString("fk_data_brg") + "'";
                    java.sql.Connection cone = (java.sql.Connection) konekdb.GetConnection();
                    java.sql.Statement pste = cone.createStatement();
                    java.sql.ResultSet res = pste.executeQuery(sql1);
                    while (res.next()) {
                        stok.setText(res.getString("stok"));
                    }
                } catch (Exception e) {
                }
            }
            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();
        } catch (Exception e) {
        }
    }

    public void simpan() {
        int ubah = Integer.parseInt(jumlah_barang.getText());
        int jml;
        try {
            String sqli = "SELECT * FROM `temp_trx_jual` WHERE id_brg='" + idk + "'";
            java.sql.Connection cone = (Connection) konekdb.GetConnection();
            java.sql.Statement sta = cone.createStatement();
            java.sql.ResultSet rs = sta.executeQuery(sqli);
            if (rs.next()) {
                harga = rs.getInt("harga");
                jml = ubah * harga;
                try {
                    String sql = "UPDATE `temp_trx_jual` "
                            + "SET `jumlah`='" + jumlah_barang.getText() + "',`total`='" + jml + "' WHERE id_brg='" + idk + "'";
                    java.sql.Connection con = (Connection) konekdb.GetConnection();
                    java.sql.PreparedStatement pst = con.prepareStatement(sql);
                    pst.execute();
                    getDesktopPane().add(new trx_jual()).setVisible(true);
                    dispose();
                } catch (Exception e) {
                }
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nama_barang = new javax.swing.JTextField();
        stok = new javax.swing.JTextField();
        jumlah_barang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nama_barang.setEditable(false);
        nama_barang.setFont(new java.awt.Font("Quicksand", 0, 17)); // NOI18N
        nama_barang.setBorder(null);
        nama_barang.setOpaque(false);
        getContentPane().add(nama_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 370, 30));

        stok.setEditable(false);
        stok.setFont(new java.awt.Font("Quicksand", 0, 17)); // NOI18N
        stok.setBorder(null);
        stok.setOpaque(false);
        getContentPane().add(stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 370, 30));

        jumlah_barang.setFont(new java.awt.Font("Quicksand", 0, 17)); // NOI18N
        jumlah_barang.setBorder(null);
        jumlah_barang.setOpaque(false);
        getContentPane().add(jumlah_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 290, 370, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trx_jual/batal.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trx_jual/simpan.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trx_jual/ubah.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.dispose();
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            simpan();
        }
    }//GEN-LAST:event_jLabel4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jumlah_barang;
    private javax.swing.JTextField nama_barang;
    private javax.swing.JTextField stok;
    // End of variables declaration//GEN-END:variables
}
