/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import javax.swing.ImageIcon;
import DataProduk.form_addProduct;
import DataProdukBarang.form_tambahProdukBarang;
import TransaksiBeli.tambah_barang_cari;
import db.konekdb;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author LenataHoma
 */
public class Mainhome extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    Statement st;
    String kategori_jasa = null; //untuk memberi kondisi pada ubah Data Jasa
    public String id_produk = null; //mengambil ID Produk agar bisa dikirim value nya ke form lain
    public Mainhome() {
        initComponents();
        panel_beranda.setVisible(false);
        panel_dataProduk.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_transaksiBeli = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pilihPemasok = new javax.swing.JLabel();
        btnTambah3 = new javax.swing.JLabel();
        btnUbah = new javax.swing.JLabel();
        btnBayar = new javax.swing.JLabel();
        btnUbah1 = new javax.swing.JLabel();
        IdTransaksi = new javax.swing.JLabel();
        namaSupplier = new javax.swing.JLabel();
        tgalTransaksi = new javax.swing.JLabel();
        idSupplier = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bg_transaksiBeli = new javax.swing.JLabel();
        Welcome_Screen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_dataProduk = new javax.swing.JPanel();
        btn_hapusProduk = new javax.swing.JLabel();
        btn_ubahProduk = new javax.swing.JLabel();
        btn_tamabahJasaProduk = new javax.swing.JLabel();
        btn_tambahProduk = new javax.swing.JLabel();
        txt_searchProduk = new javax.swing.JTextField();
        bgt_serachBox = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelProduk = new javax.swing.JTable(){

            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return false; //Disallow the editing of any cell
            }

        };
        bg_dataProduk = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        panel_beranda = new javax.swing.JPanel();
        greetingpanel = new javax.swing.JLabel();
        bg_berand = new javax.swing.JLabel();
        panel_dataStok = new javax.swing.JPanel();
        bg_dataStok = new javax.swing.JLabel();
        panel_transaksiJual = new javax.swing.JPanel();
        bg_transaksiJual = new javax.swing.JLabel();
        panel_dataPemasok = new javax.swing.JPanel();
        bg_dataPemasok = new javax.swing.JLabel();
        panel_Laporan = new javax.swing.JPanel();
        bg_Laporan = new javax.swing.JLabel();
        panel_Lainnya = new javax.swing.JPanel();
        bg_Lainnya = new javax.swing.JLabel();
        btn_lainnya = new javax.swing.JLabel();
        btn_laporan = new javax.swing.JLabel();
        btn_dataPemasok = new javax.swing.JLabel();
        btn_transjual1 = new javax.swing.JLabel();
        btn_transbeli = new javax.swing.JLabel();
        btn_dataStok = new javax.swing.JLabel();
        btn_dataProduk = new javax.swing.JLabel();
        btn_beranda = new javax.swing.JLabel();
        sidebar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(237, 237, 237));
        setForeground(new java.awt.Color(237, 237, 237));
        setMinimumSize(new java.awt.Dimension(1240, 707));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_transaksiBeli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        panel_transaksiBeli.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 850, -1));

        pilihPemasok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TransaksiBeli/1.6.png"))); // NOI18N
        panel_transaksiBeli.add(pilihPemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 110, 40));

        btnTambah3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TransaksiBeli/1.2.png"))); // NOI18N
        btnTambah3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambah3MouseClicked(evt);
            }
        });
        panel_transaksiBeli.add(btnTambah3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 110, 40));

        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TransaksiBeli/1.5.png"))); // NOI18N
        panel_transaksiBeli.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 110, 40));

        btnBayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TransaksiBeli/1.4.png"))); // NOI18N
        panel_transaksiBeli.add(btnBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 110, 40));

        btnUbah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TransaksiBeli/1.3.png"))); // NOI18N
        panel_transaksiBeli.add(btnUbah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 110, 40));

        IdTransaksi.setFont(new java.awt.Font("Quicksand Medium", 0, 17)); // NOI18N
        IdTransaksi.setText("TB/17052022/001");
        panel_transaksiBeli.add(IdTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        namaSupplier.setFont(new java.awt.Font("Quicksand Medium", 0, 17)); // NOI18N
        namaSupplier.setText("SUJAKI");
        panel_transaksiBeli.add(namaSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        tgalTransaksi.setFont(new java.awt.Font("Quicksand Medium", 0, 17)); // NOI18N
        tgalTransaksi.setText("17-05-2022");
        panel_transaksiBeli.add(tgalTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        idSupplier.setFont(new java.awt.Font("Quicksand Medium", 0, 17)); // NOI18N
        idSupplier.setText("PMS123");
        panel_transaksiBeli.add(idSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Quicksand Medium", 0, 17)); // NOI18N
        jLabel3.setText("Pemasok");
        panel_transaksiBeli.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Quicksand Medium", 0, 17)); // NOI18N
        jLabel5.setText("ID Transaksi");
        panel_transaksiBeli.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Quicksand Medium", 0, 17)); // NOI18N
        jLabel4.setText("Tanggal Transaksi");
        panel_transaksiBeli.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 140, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TransaksiBeli/1.1.png"))); // NOI18N
        panel_transaksiBeli.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 870, 200));

        bg_transaksiBeli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TransaksiBeli/formTransbeli.png"))); // NOI18N
        panel_transaksiBeli.add(bg_transaksiBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 710));

        getContentPane().add(panel_transaksiBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 960, 710));

        Welcome_Screen.setBackground(new java.awt.Color(237, 237, 237));
        Welcome_Screen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/tampilan_welcome.png"))); // NOI18N
        Welcome_Screen.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        getContentPane().add(Welcome_Screen, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 0, 960, 710));

        panel_dataProduk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_hapusProduk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_hapusProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataProduk/btn_hapusProduk.png"))); // NOI18N
        btn_hapusProduk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_hapusProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusProdukMouseClicked(evt);
            }
        });
        panel_dataProduk.add(btn_hapusProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 124, 90, 30));

        btn_ubahProduk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_ubahProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataProduk/btn_ubahProduk.png"))); // NOI18N
        btn_ubahProduk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ubahProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ubahProdukMouseClicked(evt);
            }
        });
        panel_dataProduk.add(btn_ubahProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 124, 90, -1));

        btn_tamabahJasaProduk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_tamabahJasaProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataProduk/btn_tambahJasaProduk.png"))); // NOI18N
        btn_tamabahJasaProduk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tamabahJasaProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tamabahJasaProdukMouseClicked(evt);
            }
        });
        panel_dataProduk.add(btn_tamabahJasaProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 124, 90, 30));

        btn_tambahProduk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_tambahProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataProduk/btn_tambahBarang.png"))); // NOI18N
        btn_tambahProduk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tambahProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahProdukMouseClicked(evt);
            }
        });
        panel_dataProduk.add(btn_tambahProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 124, 90, 30));

        txt_searchProduk.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        txt_searchProduk.setBorder(null);
        txt_searchProduk.setOpaque(false);
        panel_dataProduk.add(txt_searchProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 125, 290, 30));

        bgt_serachBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataProduk/searchBox.png"))); // NOI18N
        panel_dataProduk.add(bgt_serachBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 360, 60));

        jScrollPane1.setBorder(null);

        TabelProduk.setFont(new java.awt.Font("Quicksand Medium", 0, 15)); // NOI18N
        TabelProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Satuan", "Harga Beli", "Harga Jual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelProduk.setRowHeight(40);
        TabelProduk.getTableHeader().setResizingAllowed(false);
        TabelProduk.getTableHeader().setReorderingAllowed(false);
        TabelProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelProdukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelProduk);
        if (TabelProduk.getColumnModel().getColumnCount() > 0) {
            TabelProduk.getColumnModel().getColumn(0).setResizable(false);
            TabelProduk.getColumnModel().getColumn(1).setResizable(false);
            TabelProduk.getColumnModel().getColumn(4).setResizable(false);
        }

        panel_dataProduk.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 177, 860, 500));

        bg_dataProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataProduk/formDataProduk.png"))); // NOI18N
        panel_dataProduk.add(bg_dataProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 710));

        lbl_id.setEnabled(false);
        panel_dataProduk.add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 46, -1, -1));

        getContentPane().add(panel_dataProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 960, 710));

        panel_beranda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        greetingpanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greetingpanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beranda/greetingsPanel.png"))); // NOI18N
        panel_beranda.add(greetingpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 880, 220));

        bg_berand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beranda/fotmBeranda.png"))); // NOI18N
        panel_beranda.add(bg_berand, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 710));

        getContentPane().add(panel_beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 960, 710));

        panel_dataStok.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_dataStok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataStok/formDataStok.png"))); // NOI18N
        panel_dataStok.add(bg_dataStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 710));

        getContentPane().add(panel_dataStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 960, 710));

        panel_transaksiJual.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_transaksiJual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TransaksiJual/formTransjual.png"))); // NOI18N
        panel_transaksiJual.add(bg_transaksiJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 710));

        getContentPane().add(panel_transaksiJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 960, 710));

        panel_dataPemasok.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_dataPemasok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataPemasok/formDatapemasok.png"))); // NOI18N
        panel_dataPemasok.add(bg_dataPemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 710));

        getContentPane().add(panel_dataPemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 960, 710));

        panel_Laporan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_Laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Laporan/formLaporan.png"))); // NOI18N
        panel_Laporan.add(bg_Laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 710));

        getContentPane().add(panel_Laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 960, 710));

        panel_Lainnya.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_Lainnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lainnya/formLainnya.png"))); // NOI18N
        panel_Lainnya.add(bg_Lainnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 710));

        getContentPane().add(panel_Lainnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 960, 710));

        btn_lainnya.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_lainnya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lainnyaMouseClicked(evt);
            }
        });
        getContentPane().add(btn_lainnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 280, 47));

        btn_laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_laporanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 280, 47));

        btn_dataPemasok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_dataPemasok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dataPemasokMouseClicked(evt);
            }
        });
        getContentPane().add(btn_dataPemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 280, 47));

        btn_transjual1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_transjual1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_transjual1MouseClicked(evt);
            }
        });
        getContentPane().add(btn_transjual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 280, 47));

        btn_transbeli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_transbeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_transbeliMouseClicked(evt);
            }
        });
        getContentPane().add(btn_transbeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 280, 47));

        btn_dataStok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_dataStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dataStokMouseClicked(evt);
            }
        });
        getContentPane().add(btn_dataStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 280, 47));

        btn_dataProduk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_dataProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dataProdukMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dataProdukMouseEntered(evt);
            }
        });
        getContentPane().add(btn_dataProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 280, 47));

        btn_beranda.setBackground(new java.awt.Color(239, 239, 239));
        btn_beranda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_beranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_berandaMouseClicked(evt);
            }
        });
        getContentPane().add(btn_beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 280, 47));

        sidebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SideBar/sidebar_none.png"))); // NOI18N
        getContentPane().add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 283, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void blocksidebar(){
        btn_beranda.disable();
        btn_dataProduk.disable();
        btn_dataStok.disable();
        btn_transbeli.disable();
        btn_transjual1.disable();
        btn_dataPemasok.disable();
        btn_lainnya.disable();
        btn_laporan.disable();
    }
    public void loadTableProduk(){
    DefaultTableModel tbl = new DefaultTableModel();
            TabelProduk.setBorder(null);
            jScrollPane1.setBorder(null);
            tbl.addColumn("ID Produk");
            tbl.addColumn("Nama Produk");
            tbl.addColumn("Satuan");
            tbl.addColumn("Harga Dasar");
            tbl.addColumn("Harga Jual");
            TabelProduk.setModel(tbl);
            try {
                String sql = "SELECT * FROM tb_produk";
                java.sql.Connection conn = (Connection)konekdb.GetConnection();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);
                while(res.next())
                {
                    tbl.addRow(new Object[]{
                        res.getString("id_produk"),
                        res.getString("nama_produk"),
                        res.getString("satuan"),
                        res.getString("harga_beli"),
                        res.getString("harga_jual")
            });
                    
                TabelProduk.setModel(tbl);
            }
         } catch (Exception e) {
                System.out.println("Gagal mendapatkan Data!");
         }
    }
    private void btn_berandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_berandaMouseClicked
        // TODO add your handling code here:
        ImageIcon berandaclick = new ImageIcon("src/SideBar/sidebar_beranda.png");
        sidebar.setIcon(berandaclick);
        Welcome_Screen.setVisible(false);
        panel_beranda.setVisible(true);
        panel_dataProduk.setVisible(false);
        panel_dataStok.setVisible(false);
        panel_transaksiBeli.setVisible(false);
        panel_transaksiJual.setVisible(false);
        panel_dataPemasok.setVisible(false);
        panel_Laporan.setVisible(false);
        panel_Lainnya.setVisible(false);
        
    }//GEN-LAST:event_btn_berandaMouseClicked

    private void btn_dataProdukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataProdukMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dataProdukMouseEntered

    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
    
    private void btn_dataProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataProdukMouseClicked
        // TODO add your handling code here:
        ImageIcon produk = new ImageIcon("src/SideBar/sidebar_dataProduk.png");
        sidebar.setIcon(produk);
        
        loadTableProduk();
        TabelProduk.setVisible(true);
        TabelProduk.getTableHeader().disable();
        jScrollPane1.setVisible(true);
        Welcome_Screen.setVisible(false);
        panel_beranda.setVisible(false);
        panel_dataProduk.setVisible(true);
        panel_beranda.setVisible(false);
        panel_dataProduk.setVisible(true);
        panel_dataStok.setVisible(false);
        panel_transaksiBeli.setVisible(false);
        panel_transaksiJual.setVisible(false);
        panel_dataPemasok.setVisible(false);
        panel_Laporan.setVisible(false);
        panel_Lainnya.setVisible(false);
        
    }//GEN-LAST:event_btn_dataProdukMouseClicked

    private void btn_dataStokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataStokMouseClicked
        // TODO add your handling code here:
        ImageIcon stok = new ImageIcon("src/SideBar/sidebar_dataStok.png");
        sidebar.setIcon(stok);
        Welcome_Screen.setVisible(false);
        panel_beranda.setVisible(false);
        panel_dataProduk.setVisible(false);
        panel_dataStok.setVisible(true);
        panel_transaksiBeli.setVisible(false);
        panel_transaksiJual.setVisible(false);
        panel_dataPemasok.setVisible(false);
        panel_Laporan.setVisible(false);
        panel_Lainnya.setVisible(false);
        
    }//GEN-LAST:event_btn_dataStokMouseClicked

    private void btn_transbeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transbeliMouseClicked
        // TODO add your handling code here:
        ImageIcon transbeli = new ImageIcon("src/SideBar/sidebar_transbeli.png");
        sidebar.setIcon(transbeli);
        Welcome_Screen.setVisible(false);
        panel_beranda.setVisible(false);
        panel_dataProduk.setVisible(false);
        panel_dataStok.setVisible(false);
        panel_transaksiBeli.setVisible(true);
        panel_transaksiJual.setVisible(false);
        panel_dataPemasok.setVisible(false);
        panel_Laporan.setVisible(false);
        panel_Lainnya.setVisible(false);
    }//GEN-LAST:event_btn_transbeliMouseClicked

    private void btn_transjual1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transjual1MouseClicked
        // TODO add your handling code here:
        ImageIcon transjual = new ImageIcon("src/SideBar/sidebar_transjual.png");
        sidebar.setIcon(transjual);
        Welcome_Screen.setVisible(false);
        panel_beranda.setVisible(false);
        panel_dataProduk.setVisible(false);
        panel_dataStok.setVisible(false);
        panel_transaksiBeli.setVisible(false);
        panel_transaksiJual.setVisible(true);
        panel_dataPemasok.setVisible(false);
        panel_Laporan.setVisible(false);
        panel_Lainnya.setVisible(false);
    }//GEN-LAST:event_btn_transjual1MouseClicked

    private void btn_dataPemasokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataPemasokMouseClicked
        // TODO add your handling code here:
        ImageIcon pemasok = new ImageIcon("src/SideBar/side_dataPemasok.png");
        sidebar.setIcon(pemasok);
        Welcome_Screen.setVisible(false);
        panel_beranda.setVisible(false);
        panel_dataProduk.setVisible(false);
        panel_dataStok.setVisible(false);
        panel_transaksiBeli.setVisible(false);
        panel_transaksiJual.setVisible(false);
        panel_dataPemasok.setVisible(true);
        panel_Laporan.setVisible(false);
        panel_Lainnya.setVisible(false);
    }//GEN-LAST:event_btn_dataPemasokMouseClicked

    private void btn_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseClicked
        // TODO add your handling code here:
        ImageIcon laporan = new ImageIcon("src/SideBar/sidebar_laporan.png");
        sidebar.setIcon(laporan);
        Welcome_Screen.setVisible(false);
        panel_beranda.setVisible(false);
        panel_dataProduk.setVisible(false);
        panel_dataStok.setVisible(false);
        panel_transaksiBeli.setVisible(false);
        panel_transaksiJual.setVisible(false);
        panel_dataPemasok.setVisible(false);
        panel_Laporan.setVisible(true);
        panel_Lainnya.setVisible(false);
    }//GEN-LAST:event_btn_laporanMouseClicked

    private void btn_lainnyaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lainnyaMouseClicked
        // TODO add your handling code here:
        ImageIcon laporan = new ImageIcon("src/SideBar/sidebar_lainnya.png");
        sidebar.setIcon(laporan);
        Welcome_Screen.setVisible(false);
        panel_beranda.setVisible(false);
        panel_dataProduk.setVisible(false);
        panel_dataStok.setVisible(false);
        panel_transaksiBeli.setVisible(false);
        panel_transaksiJual.setVisible(false);
        panel_dataPemasok.setVisible(false);
        panel_Laporan.setVisible(false);
        panel_Lainnya.setVisible(true);
    }//GEN-LAST:event_btn_lainnyaMouseClicked

    private void btn_tambahProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahProdukMouseClicked
         // TODO add your handling code here:
//         TabelProduk.setVisible(false);
//         jScrollPane1.setVisible(false);
//         panel_tambahProdukBarang.setVisible(true);
//         panel_notifBerhasilProdukBarang.setVisible(false);
//         blocksidebar();
//         txt_searchProduk.setEnabled(false);
//         panel_notifwarnkodeprodukBarang.setVisible(false);
//         panel_notifwarnnamaprodukBarang.setVisible(false);
//         panel_notifwarnsatuanprodukbarang.setVisible(false);
//         panel_notifwarnhargabeliprodukbarang.setVisible(false);
//         panel_notifwarnhargajualprodukbarang.setVisible(false);
//         DataProdukBarang.form_tambahProdukBarang brg = new form_tambahProdukBarang();
//         brg.setVisible(true);
        DataProdukBarang.formTambahProdukBarang brg = new DataProdukBarang.formTambahProdukBarang(this, true);
        brg.setVisible(true);
         txt_searchProduk.setEnabled(false);
         
    }//GEN-LAST:event_btn_tambahProdukMouseClicked

    private void TabelProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelProdukMouseClicked
        // TODO add your handling code here:
        int baris= TabelProduk.rowAtPoint(evt.getPoint());
        kategori_jasa = TabelProduk.getValueAt(baris, 2).toString();
        id_produk = TabelProduk.getValueAt(baris, 0).toString();
        System.out.println("ID PRODUK = "+id_produk);
        System.out.println("Kategori "+ kategori_jasa);
        lbl_id.setText(id_produk);
//        int i = TabelProduk.getSelectedRow();
//        TableModel tm = TabelProduk.getModel();
//        DataProdukJasa.formUbahJasa mn = new DataProdukJasa.formUbahJasa(this, true);
//        id_produk= tm.getValueAt(i, 0).toString();
//        mn.txt_kodeProdukJasa.setText(id_produk);
    }//GEN-LAST:event_TabelProdukMouseClicked

    public String getId_produk(){
        return id_produk;
    }
    public void setIdProdukJasanull(String id_produk){
        this.id_produk = id_produk;
    }
    public void setKategorinull(String catJasa){
        this.kategori_jasa = catJasa;
    }
    public void auto_kode(){
//        try {
//             String sql = "SELECT * FROM `tb_produk` WHERE tb_produk.satuan = 'jasa'\n"
//                    + "ORDER BY id_produk DESC;";
//             con = (Connection)konekdb.GetConnection();
//             st = con.createStatement();
//             rs = st.executeQuery(sql);
//             if (rs.next()) {
//                String kode_jasa = rs.getString("id_produk").substring(1);
//                String AK = "" + (Integer.parseInt(kode_jasa)+ 1);
//                String Nol = "";
//                
//                 if (AK.length() == 1) {
//                     Nol = "00";
//                 } else if (AK.length() == 2) {
//                     Nol = "0";
//                 } else if (AK.length() == 3) {
//                     Nol = "";
//                 }
//                txt_kodeprodukTambahProdukJasa.setText("JASA" + Nol + AK);//sesuaikan dengan variable namenya
//            } else {
//                txt_kodeprodukTambahProdukJasa.setText("JASA001");//sesuaikan dengan variable namenya
//            }
//            
//       } catch (Exception e) {
//           System.err.println(e.getMessage());
//       }
        
    }
    private void btn_tamabahJasaProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tamabahJasaProdukMouseClicked
        // TODO add your handling code here:
        
//        TabelProduk.setVisible(false);
//        jScrollPane1.setVisible(false);
//        panel_tambahProdukJasa.setVisible(true);
        txt_searchProduk.setEnabled(false);
//        panel_notifBerhasilProdukJasa.setVisible(false);
        DataProdukJasa.formTambahJasa tj = new DataProdukJasa.formTambahJasa(this, true);
        tj.setVisible(true);
    }//GEN-LAST:event_btn_tamabahJasaProdukMouseClicked

    
    
    
    private void btn_ubahProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ubahProdukMouseClicked
        // TODO add your handling code here:
        if(kategori_jasa==null){
            JOptionPane.showMessageDialog(null, "Harap Pilih data Produk!");
        } else if(kategori_jasa.equals("jasa")){
            DataProdukJasa.formUbahJasa tj = new DataProdukJasa.formUbahJasa(this, true);
            
            tj.txt_kodeProdukJasa.setText(getId_produk());
            tj.setVisible(true);
            
            System.out.println("btn ubah : " + getId_produk());
        } else {
            
            DataProdukBarang.formUbahProdukBarang ub = new DataProdukBarang.formUbahProdukBarang(this, true);
            ub.txt_kodeProdukBarang.setText(getId_produk());
            ub.setVisible(true);
            
            System.out.println("btn ubah = "+ getId_produk());
        }
    }//GEN-LAST:event_btn_ubahProdukMouseClicked

    private void btn_hapusProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusProdukMouseClicked
        // TODO add your handling code here:
        if (id_produk==null) {
            JOptionPane.showMessageDialog(null, "Harap Pilih data Produk!");
        } else if(kategori_jasa.equals("jasa")){
            DataProdukJasa.notif_warninghapusProdukJasa tj = new DataProdukJasa.notif_warninghapusProdukJasa(this, false);
            tj.setVisible(true);
        } else {
            DataProdukBarang.notif_warningHapusProdukBarang pb = new DataProdukBarang.notif_warningHapusProdukBarang(this, false);
            pb.setVisible(true);
        }
    }//GEN-LAST:event_btn_hapusProdukMouseClicked

    private void btnTambah3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambah3MouseClicked
        // TODO add your handling code here:
        tambah_barang_cari tambar = new tambah_barang_cari(this, true);
        tambar.setVisible(true);
    }//GEN-LAST:event_btnTambah3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login.Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdTransaksi;
    public static javax.swing.JTable TabelProduk;
    private javax.swing.JPanel Welcome_Screen;
    private javax.swing.JLabel bg_Lainnya;
    private javax.swing.JLabel bg_Laporan;
    private javax.swing.JLabel bg_berand;
    private javax.swing.JLabel bg_dataPemasok;
    private javax.swing.JLabel bg_dataProduk;
    private javax.swing.JLabel bg_dataStok;
    private javax.swing.JLabel bg_transaksiBeli;
    private javax.swing.JLabel bg_transaksiJual;
    private javax.swing.JLabel bgt_serachBox;
    private javax.swing.JLabel btnBayar;
    private javax.swing.JLabel btnTambah3;
    private javax.swing.JLabel btnUbah;
    private javax.swing.JLabel btnUbah1;
    private javax.swing.JLabel btn_beranda;
    private javax.swing.JLabel btn_dataPemasok;
    private javax.swing.JLabel btn_dataProduk;
    private javax.swing.JLabel btn_dataStok;
    private javax.swing.JLabel btn_hapusProduk;
    private javax.swing.JLabel btn_lainnya;
    private javax.swing.JLabel btn_laporan;
    private javax.swing.JLabel btn_tamabahJasaProduk;
    private javax.swing.JLabel btn_tambahProduk;
    private javax.swing.JLabel btn_transbeli;
    private javax.swing.JLabel btn_transjual1;
    public static javax.swing.JLabel btn_ubahProduk;
    private javax.swing.JLabel greetingpanel;
    private javax.swing.JLabel idSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public static javax.swing.JLabel lbl_id;
    private javax.swing.JLabel namaSupplier;
    private javax.swing.JPanel panel_Lainnya;
    private javax.swing.JPanel panel_Laporan;
    private javax.swing.JPanel panel_beranda;
    private javax.swing.JPanel panel_dataPemasok;
    private javax.swing.JPanel panel_dataProduk;
    private javax.swing.JPanel panel_dataStok;
    private javax.swing.JPanel panel_transaksiBeli;
    private javax.swing.JPanel panel_transaksiJual;
    private javax.swing.JLabel pilihPemasok;
    private javax.swing.JLabel sidebar;
    private javax.swing.JLabel tgalTransaksi;
    private javax.swing.JTextField txt_searchProduk;
    // End of variables declaration//GEN-END:variables
}
