/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trxx_beli;

/**
 *
 * @author LENOVO
 */
public class b_tambah_panel extends javax.swing.JPanel {

    /**
     * Creates new form b_tambah_panel
     */
    public b_tambah_panel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cari_barang = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JLabel();
        tex_kode_barang = new javax.swing.JTextField();
        tex_kode_barang1 = new javax.swing.JTextField();
        tex_kode_barang2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gambar_tambah_barang = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cari_barang.setFont(new java.awt.Font("Quicksand Medium", 0, 17)); // NOI18N
        btn_cari_barang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_cari_barang.setText("Cari Barang");
        add(btn_cari_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 130, 30));

        btn_hapus.setFont(new java.awt.Font("Quicksand Medium", 0, 17)); // NOI18N
        btn_hapus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_hapus.setText("Batal");
        add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 130, 30));

        btn_simpan.setFont(new java.awt.Font("Quicksand Medium", 0, 17)); // NOI18N
        btn_simpan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_simpan.setText("Simpan");
        add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 130, 30));

        tex_kode_barang.setFont(new java.awt.Font("Quicksand", 0, 17)); // NOI18N
        tex_kode_barang.setBorder(null);
        tex_kode_barang.setOpaque(false);
        tex_kode_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tex_kode_barangActionPerformed(evt);
            }
        });
        add(tex_kode_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 350, 40));

        tex_kode_barang1.setFont(new java.awt.Font("Quicksand", 0, 17)); // NOI18N
        tex_kode_barang1.setBorder(null);
        tex_kode_barang1.setOpaque(false);
        tex_kode_barang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tex_kode_barang1ActionPerformed(evt);
            }
        });
        add(tex_kode_barang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 350, 40));

        tex_kode_barang2.setFont(new java.awt.Font("Quicksand", 0, 17)); // NOI18N
        tex_kode_barang2.setBorder(null);
        tex_kode_barang2.setOpaque(false);
        tex_kode_barang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tex_kode_barang2ActionPerformed(evt);
            }
        });
        add(tex_kode_barang2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 350, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trxx_beli/gmbr_button_bayar.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trxx_beli/gmbr_button_bayar.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 130, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trxx_beli/gmbr_button_hapus.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 130, 30));

        gambar_tambah_barang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trxx_beli/gmbr_tambahBEli.png"))); // NOI18N
        add(gambar_tambah_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 410));
    }// </editor-fold>//GEN-END:initComponents

    private void tex_kode_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tex_kode_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tex_kode_barangActionPerformed

    private void tex_kode_barang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tex_kode_barang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tex_kode_barang1ActionPerformed

    private void tex_kode_barang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tex_kode_barang2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tex_kode_barang2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_cari_barang;
    private javax.swing.JLabel btn_hapus;
    private javax.swing.JLabel btn_simpan;
    private javax.swing.JLabel gambar_tambah_barang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tex_kode_barang;
    private javax.swing.JTextField tex_kode_barang1;
    private javax.swing.JTextField tex_kode_barang2;
    // End of variables declaration//GEN-END:variables
}
