/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trxx_beli;

import db.konekdb;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author LENOVO
 */
public class b_tamb_panel extends javax.swing.JFrame {

    public String id_barangs;

    /**
     * Creates new form b_tamb_panel
     */
    public b_tamb_panel() {
        initComponents();
        setLocationRelativeTo(null);
        load_list();
        automatic();

    }

    public void load_list() {
        try {
            String sql = "SELECT * FROM `tb_barang`";
            java.sql.Connection con = (Connection) konekdb.GetConnection();
            java.sql.Statement st = con.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                jComboBox1.addItem(rs.getString(1));
            }
        } catch (Exception e) {
        }
    }

    public void automatic() {  //Otomatis id transaksi, jika tanggal ganti kembali ke 1 lagi
        try {
            DateFormat hari = new SimpleDateFormat("yyyy-MM-dd");
            String a = hari.format(Calendar.getInstance().getTime());

            String sql = "SELECT MAX(right(id_brg,6)) AS ambil "
                    + "FROM temp_trx_beli Where tgl like '" + a + "';";
            java.sql.Connection con = (java.sql.Connection) konekdb.GetConnection();
            java.sql.Statement pst = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            while (rs.next()) {
                if (rs.first() == true) //                {
                //                    id = "id_0000001";
                //                } else 
                {
                    rs.last();
                    int auto_id = rs.getInt(1) + 1;
                    String no = String.valueOf(auto_id);
                    int NomorJual = no.length();
                    //MENGATUR jumlah 0
                    for (int j = 0; j < 6 - NomorJual; j++) {
                        no = "0" + no;
                    }
                    id_barangs = "id_" + no;
                }
            }
        } catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        btn_hapus = new javax.swing.JLabel();
        btn_cari_barang = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JLabel();
        jumlah_brg = new javax.swing.JTextField();
        nama_brg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gambar_tambah_barang = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 350, 40));

        btn_hapus.setFont(new java.awt.Font("Quicksand Medium", 0, 17)); // NOI18N
        btn_hapus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_hapus.setText("Batal");
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 130, 30));

        btn_cari_barang.setFont(new java.awt.Font("Quicksand Medium", 0, 17)); // NOI18N
        btn_cari_barang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_cari_barang.setText("Cari Barang");
        btn_cari_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cari_barangMouseClicked(evt);
            }
        });
        getContentPane().add(btn_cari_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 130, 30));

        btn_simpan.setFont(new java.awt.Font("Quicksand Medium", 0, 17)); // NOI18N
        btn_simpan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_simpan.setText("Simpan");
        btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 130, 30));

        jumlah_brg.setFont(new java.awt.Font("Quicksand", 0, 17)); // NOI18N
        jumlah_brg.setBorder(null);
        jumlah_brg.setOpaque(false);
        getContentPane().add(jumlah_brg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 350, 40));

        nama_brg.setFont(new java.awt.Font("Quicksand", 0, 17)); // NOI18N
        nama_brg.setBorder(null);
        nama_brg.setOpaque(false);
        getContentPane().add(nama_brg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 350, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trxx_beli/gmbr_button_bayar.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trxx_beli/gmbr_button_bayar.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 130, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trxx_beli/gmbr_button_hapus.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 130, 30));

        gambar_tambah_barang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trxx_beli/gmbr_tambahBEli.png"))); // NOI18N
        getContentPane().add(gambar_tambah_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cari_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cari_barangMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            new ba_car_barang().setVisible(true);
        }
    }//GEN-LAST:event_btn_cari_barangMouseClicked

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "select * from `tb_barang` where id_barang='" + jComboBox1.getSelectedItem() + "'";
            java.sql.Connection con = (Connection) konekdb.GetConnection();
            java.sql.Statement st = con.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                nama_brg.setText(rs.getString("nama_barang"));
                jumlah_brg.setText("0");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseClicked
        String nama;
        int harga, jml, ttl;
        DateFormat hari = new SimpleDateFormat("yyyy-MM-dd");
        String a = hari.format(Calendar.getInstance().getTime());
        if (evt.getButton() == MouseEvent.BUTTON1) {
            try {
                String sql1 = "SELECT * FROM tb_barang WHERE id_barang = '" + jComboBox1.getSelectedItem() + "'";

                java.sql.Connection con = (Connection) konekdb.GetConnection();
                java.sql.Statement st = con.createStatement();
                java.sql.ResultSet rs = st.executeQuery(sql1);
                if (rs.next()) {
                    nama = rs.getString("nama_barang");
                    harga = rs.getInt("harga_jual");
                    jml = Integer.parseInt(jumlah_brg.getText());
                    ttl = harga * jml;
                    try {
                         String sql = "INSERT INTO `temp_trx_beli`(`id_brg`, `nama_brg`, `harga_jual`, "
                                + "`jumlah`, `total_harga`, `tanggal`, `fk_data_brg`, `id_trx`) VALUES "
                                + "('" + id_barangs + "','" + nama + "','" + harga + "',"
                                + "'" + jml + "','" + ttl + "','" + a + "','"+jComboBox1.getSelectedItem()+"','"+a_transbeli_utama.jLabel4.getText()+"')";
                        java.sql.PreparedStatement ps = con.prepareStatement(sql);
                        ps.execute();
                        this.dispose();
                    } catch (Exception e) {
                    }

                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btn_simpanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(b_tamb_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(b_tamb_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(b_tamb_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(b_tamb_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new b_tamb_panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_cari_barang;
    private javax.swing.JLabel btn_hapus;
    private javax.swing.JLabel btn_simpan;
    private javax.swing.JLabel gambar_tambah_barang;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jumlah_brg;
    private javax.swing.JTextField nama_brg;
    // End of variables declaration//GEN-END:variables
}
