/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trxx_beli;

/**
 *
 * @author LENOVO
 */
public class d_simpan_pembelian extends javax.swing.JPanel {

    /**
     * Creates new form d_simpan_pembelian
     */
    public d_simpan_pembelian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 360, 40));

        jTextField2.setBorder(null);
        jTextField2.setOpaque(false);
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 360, 30));

        jTextField3.setBorder(null);
        jTextField3.setOpaque(false);
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 360, 40));

        jTextField4.setBorder(null);
        jTextField4.setOpaque(false);
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 360, 30));

        jLabel5.setFont(new java.awt.Font("Quicksand", 0, 17)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Batal");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 130, 40));

        jLabel4.setFont(new java.awt.Font("Quicksand", 0, 17)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Simpan");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 130, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trxx_beli/gmbr_button_bayar.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 130, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trxx_beli/gmbr_button_hapus.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trxx_beli/gmbr__simpanBeli.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 420));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
